services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:80"
    depends_on:
      - db
      - migration
    volumes:
      - .:/todos/

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: alembic upgrade head

  loaded:
    depends_on:
      - api
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host=http://api:80

  db:
    image: postgres:12.2-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=todos
      - POSTGRES_PASSWORD=todos
      - POSTGRES_DB=todos
    volumes:
      - postgres-primary-data:/var/lib/postgresql
      - ./conf/setup.sh:/docker-entrypoint-initdb.d/setup.sh
  slave:
    image: postgres:12.2-alpine
    ports:
      - "5434:5432"
    depends_on:
      - db
    restart: always
    environment:
      - POSTGRES_USER=todos
      - POSTGRES_PASSWORD=todos
      - POSTGRES_DB=todos
    volumes:
      - ./conf/slave-setup.sh:/docker-entrypoint-initdb.d/slave-setup.sh
      - postgres-slave-data:/var/lib/postgresql

volumes:
  postgres-primary-data:
    driver: local
  postgres-slave-data:
    driver: local